stages:
  - sync
  
sync_to_github:
  stage: sync
  image: lsage/pnpm-circleci-node:16.13.1-pnpm7.5.1
  variables:
    GIT_STRATEGY: clone
  script:
    - git config --global user.email "chenzhuo9729@gmail.com"
    - git config --global user.name "nigo299"
    
    # 主仓库同步
    - git remote add github https://${GITHUB_TOKEN}@github.com/nigo299/spider-clould-init.git
    - git push github HEAD:main --force
    - git push github --tags
    
    # 子模块处理
    - |
      git submodule foreach '
        SUBMODULE_NAME=$(basename $name)
        echo "Processing submodule: $SUBMODULE_NAME"
        
        git remote add github https://${GITHUB_TOKEN}@github.com/nigo299/$SUBMODULE_NAME.git || true
        git push github HEAD:main --force
        
        cd $toplevel/$name
        git push github HEAD:main --force
        cd $toplevel
      '
    
    # 更新 .gitmodules 文件中的 URL
    - sed -i 's|http://gitlab.cqlvc.com/spider-cloud/|https://github.com/nigo299/|g' .gitmodules
    - git add .gitmodules
    - git commit -m "Update submodule URLs for GitHub" || true
    - git push github HEAD:main --force
    
    # 确保子模块更新
    - git submodule sync
    - git submodule update --init --recursive
    - git push github HEAD:main --force
    
    # 验证子模块状态
    - git submodule status
  only:
    - main  # 或者您想要触发同步的分支
  tags:
    - share-beta-fe-package-runner

