name: Publish Package to npm

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Update submodules
        run: |
          git submodule update --init --recursive
          git submodule foreach git pull origin main
      
      - name: Bump version
        run: |
          git config --local user.email "chenzhuo9729@gmail.com"
          git config --local user.name "nigo299"
          npm version patch -m "Bump version to %s"
      
      - name: Push changes
        run: |
          git push
          git push --tags
      
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}