name: Publish Package to npm

on:
  push:
    branches:
      - main  # 当 main 分支有推送时触发

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build # 如果您的项目需要构建
      
      - name: Bump version
        run: |
          git config --local user.email "chenzhuo9729@gmail.com"
          git config --local user.name "nigo299"
          npm version patch -m "Bump version to %s"
      
      - name: Push changes
        run: |
          git push
          git push --tags
      
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}