name: Publish Package to npm

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Get version from package.json
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
      - name: Check if version changed
        id: version-changed
        run: |
          LATEST_VERSION=$(npm view @lc-frontend/spider-cloud-init version || echo "0.0.0")
          if [ "${{ steps.package-version.outputs.version }}" != "$LATEST_VERSION" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Create and push tag
        if: steps.version-changed.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag v${{ steps.package-version.outputs.version }}
          git push origin v${{ steps.package-version.outputs.version }}
      
      - name: Publish to npm
        if: steps.version-changed.outputs.changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      
      - name: Version unchanged
        if: steps.version-changed.outputs.changed == 'false'
        run: echo "Version unchanged. Skipping publish."